ecomproject/cart_app/urls.py
from django.urls import path

from . import views
app_name='cart'

urlpatterns = [

    path('',views.cart_detail,name='cart_detail'),
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('remove/<int:product_id>/',views.remove_cart,name='remove_cart'),
    path('full_remove/<int:product_id>/',views.full_remove,name='full_remove')


]

ecomproject/ecomapp/urls.py
from django.urls import path

from . import views
app_name='shop'

urlpatterns = [

    path('',views.allprodcat,name='allprodcat'),
    path('<slug:c_slug>/',views.allprodcat,name='allprodcat'),
    path('<slug:c_slug>/<slug:product_slug>',views.prodetail,name='prodetail'),

]

ecomproject/ecomproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('ecomapp.urls')),
    path('search/', include('search_app.urls')),
    path('cart/',include('cart_app.urls')),


]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecomproject/search_app/urls.py
from django.urls import path

from . import views
app_name='search'

urlpatterns = [

    path('',views.search_result,name='search_result')

]

ecomproject/cart_app/models.py
from django.db import models
from ecomapp.models import Product

# Create your models here.
class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now_add=True)

    class Meta:
        db_table='Cart'
        ordering=['date_added']

    def __str__(self):
        return self.cart_id

class CartItem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)

    class Meta:
        db_table='CartItem'

    def sub_total(self):
        return self.product.price * self.quantity
    def __str__(self):
        return self.product

ecomproject/ecomapp/models.py
from django.urls import reverse
from django.db import models

# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    desc=models.TextField(blank=True)
    img=models.ImageField(upload_to='category',blank=True)

    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='categories'

    def get_url(self):

        return reverse('shop:allprodcat',args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)
class Product(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    desc=models.TextField(blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    img = models.ImageField(upload_to='product', blank=True)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    class Meta:
        ordering=('name',)
        verbose_name='product'
        verbose_name_plural='products'

    def get_url(self):

        return reverse('shop:prodetail',args=[self.category.slug,self.slug])



    def __str__(self):
        return '{}'.format(self.name)

ecomproject/search_app/models.py
from django.db import models

# Create your models here.

ecomproject/cart_app/views.py
from django.shortcuts import render,redirect,get_object_or_404
from ecomapp.models import Product
from . models import Cart,CartItem
from django.core.exceptions import ObjectDoesNotExist
# Create your views here.



def _cart_id(request):
    cart=request.session.session_key
    if not cart:
        cart=request.session.create()
    return cart

def add_cart(request,product_id):
    product=Product.objects.get(id=product_id)
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart=Cart.objects.create(
            cart_id=_cart_id(request)

        )
        cart.save()
    try:
        cart_item=CartItem.objects.get(product=product,cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity+=1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item=CartItem.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
        cart_item.save()
    return redirect('cart:cart_detail')
def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
        cart_items=CartItem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total+=(cart_item.product.price*cart_item.quantity)
            counter+= cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request,'shopping-cart.html',dict(cart_items=cart_items,total=total,counter=counter))


def remove_cart(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()

    else:
        cart_item.delete()
    return redirect('cart:cart_detail')
def full_remove(request,product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

ecomproject/ecomapp/views.py
from django.shortcuts import render,get_object_or_404
from django.db.models import Q
from .models import Category, Product
from django.core.paginator import Paginator,EmptyPage,InvalidPage


# Create your views here.
def allprodcat(request,c_slug=None):
    c_page=None
    products_list=None
    if c_slug!=None:
        c_page=get_object_or_404(Category,slug=c_slug)
        products_list=Product.objects.all().filter(category=c_page,available=True)
    else:
        products_list=Product.objects.all().filter(available=True)
    paginator=Paginator(products_list,2)
    try:
        page=int(request.GET.get('page',1))
    except:
        page=1
    try:
        products=paginator.page(page)
    except (EmptyPage,InvalidPage):
        products=paginator.page(paginator.num_pages)

    return render(request,'home.html',{'category':c_page,'products':products})

def prodetail(request,c_slug,product_slug):
    try:
        product=Product.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
        raise e

    return render(request,'product-detail.html',{'product':product})

ecomproject/search_app/views.py
from django.db.models import Q
from django.shortcuts import render
from ecomapp.models import Product


# Create your views here.
def search_result(request):
    products=None
    query=None
    if 'q' in request.GET:
        query= request.GET.get('q')
        products=Product.objects.all().filter(Q(name__contains=query) | Q(desc__contains=query))
        return render(request, 'search.html', {'query': query, 'products': products})

ecomproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>base</title>
    <script src="https://kit.fontawesome.com/1b99dd44bf.js" crossorigin="anonymous"></script>
</head>
<body>
{% include 'header.html' %}
{% include 'navbar.html' %}
{% block content %}
{% endblock %}
{% include 'footer.html' %}
</body>
</html>

ecomproject/templates/cart.html
{% extends 'base.html' %}
{% block content %}
{% if not cart_items %}
    <h3>your hopping cart i empty</h3>
    <p>please click <a href="{% url 'shop:allprodcat' %}">here</a></p>
{% else %}
{% for cart_item in cart_items %}
<br>
<a href="cart_item.product.get_absolute_url"><img src="{{cart_item.product.img.url}}"></a>
<p>{{cart_item.product.name}}</p>
sku:<p>{{cart_item.product.price}}</p>
price:$<p>{{cart_item.product.price}}</p>
qty:<p>{{cart_item.product.quantity}} * $ {{cart_item.product.price}}</p>
subtotal: {{cart_item.sub_total}}
{% if cart_item.quantity < cart_item.product.stock %}
    <a href="{% url 'cart:add_cart' cart_item.product.id %}"><i class="fa-solid fa-square-plus"></i></a>
    <a href="{% url 'cart:remove_cart' cart_item.product.id  %}"><i class="fa-solid fa-minus"></i></a><a href=""><i class="fa-solid fa-delete-left"></i></a>
     <a href="{% url 'cart:full_remove' cart_item.product.id  %}"><i class="fa-solid fa-delete-left"></i></a>
{% else %}
     <a href="{% url 'cart:remove_cart' cart_item.product.id  %}"><i class="fa-solid fa-minus"></i></a>
     <a href="{% url 'cart:full_remove' cart_item.product.id  %}"><i class="fa-solid fa-delete-left"></i></a>

{% endif %}
{% endfor %}
{% endif %}
<p>Total:{{total}}</p>
{% endblock %}

ecomproject/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    {% if category %}

            <p><a href="{% url 'shop:allprodcat' %}">Our Product COLLECTIONS</a></p>

    {% endif %}

    {% if category %}
        <img src="{{cat.image.url}}">
        <h1>{{cat.name}}</h1>
        <p>{{cat.description}}</p>

    {% else %}
      <h4>our product collections</h4>
    {% endif %}


    {% for product in products.object_list %}
        <h3>{{product.name}}</h3>

        <a href="{{product.get_url}}"><img src="{{product.img.url}}"></a>

        <p>{{product.desc}}</p>
    {% endfor %}
<div class="mx-auto">
  {% if products.paginator.num_pages > 1 %}
    <div class="text-center">
        {% for pg in products.paginator.page_range %}
        <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>
        {% endfor %}
    </div>
    {% endif %}
</div>


{% endblock %}

ecomproject/templates/footer.html
<div>
    <p>copyright</p>
</div>

ecomproject/templates/header.html
{% load static %}
<nav class="navbar navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="#">
            <img src="https://mdbcdn.b-cdn.net/img/logo/mdb-transaprent-noshadows.webp"
                 height="30"
                 alt="MDB Logo"
                 loading="lazy" />
        </a>
    </div>
</nav>

ecomproject/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>index</title>
</head>
<body>
i am index
</body>
</html>

ecomproject/templates/navbar.html
<nav>
    <ul>
        <li><a href="{% url 'shop:allprodcat' %}">All Products</a></li>
        {% for cat in  links %}
        <li><a href="{{cat.get_url}}">{{cat.name}}</a></li>
        {% endfor %}
        {% if item_count > 0 %}
        <a href="{% url 'cart:cart_detail' %}"><li>your cart</li>{{item_count}}</a>
        {% endif %}

    </ul>
    <form class="form-inline" action="{% url 'search:search_result'  %}" method="get">
      {% csrf_token %}
  <input class="form-control form-control-sm ml-3 w-75" type="text" placeholder="Search"
    aria-label="Search">
        <button class="btn btn-outline-success" type="submit">search</button>
</form>
</nav>

ecomproject/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<a href="{% url 'shop:allprodcat' %}">Home</a>
<img src="{{product.img.url}}">
<h3>{{product.name}}</h3>
<p>{{product.desc}}</p>
<p>{{product.stock}}</p>
<p>{{product.price}}</p>
{% if product.stock <= 0 %}
<p><b>out of stock</b></p>
{% else %}
<a href="{% url 'cart:add_cart' product.id %}">add to cart</a>
{% endif %}
{% endblock %}

ecomproject/templates/search.html
<p>you have searched for<b>{{query}}</b></p>
{% for product in products %}
        <h3>{{product.name}}</h3>

        <a href="{{product.get_url}}"><img src="{{product.img.url}}"></a>

        <p>{{product.desc}}</p>
{% empty %}
     <p>no products found</p>
{% endfor %}

ecomproject/templates/shopping-cart.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>Material Design for Bootstrap</title>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css" />
    <!-- Google Fonts Roboto -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap" />
    <!-- MDB -->
    <link rel="stylesheet" href="{% static 'css/mdb.min.css' %}" />
    <!-- Custom styles -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />

</head>
<body>
    <header>
  <!-- Jumbotron -->
  <div class="p-3 text-center bg-white border-bottom">
    <div class="container">
      <div class="row gy-3">
        <!-- Left elements -->
        <div class="col-lg-2 col-sm-4 col-4">
          <a href="https://mdbootstrap.com/" target="_blank" class="float-start">
            <img src="https://mdbootstrap.com/img/logo/mdb-transaprent-noshadows.png" height="35" />
          </a>
        </div>
        <!-- Left elements -->

        <!-- Center elements -->
        <div class="order-lg-last col-lg-5 col-sm-8 col-8">
          <div class="d-flex float-end">
            <a href="https://github.com/mdbootstrap/bootstrap-material-design" class="me-1 border rounded py-1 px-3 nav-link d-flex align-items-center" target="_blank">
              <i class="fas fa-user-alt m-1 me-md-2"></i>
              <p class="d-none d-md-block mb-0">Sign in</p>
            </a>
            <a href="https://github.com/mdbootstrap/bootstrap-material-design" class="me-1 border rounded py-1 px-3 nav-link d-flex align-items-center" target="_blank">
              <i class="fas fa-heart m-1 me-md-2"></i>
              <p class="d-none d-md-block mb-0">Wishlist</p>
            </a>
            <a href="{% url 'cart:cart_detail' %}" class="border rounded py-1 px-3 nav-link d-flex align-items-center" target="_blank">
              <i class="fas fa-shopping-cart m-1 me-md-2"></i>
              <p class="d-none d-md-block mb-0">My cart({{item_count}})</p>
            </a>
          </div>
        </div>
        <!-- Center elements -->

        <!-- Right elements -->
        <div class="col-lg-5 col-md-12 col-12">
          <div class="input-group float-center">
            <div class="form-outline">
              <input type="search" id="form1" class="form-control" />
              <label class="form-label" for="form1">Search</label>
            </div>
            <button type="button" class="btn btn-primary shadow-0">
              <i class="fas fa-search"></i>
            </button>
          </div>
        </div>
        <!-- Right elements -->
      </div>
    </div>
  </div>
  <!-- Jumbotron -->
      <!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-light bg-white">
    <!-- Container wrapper -->
    <div class="container justify-content-center justify-content-md-between">
      <!-- Toggle button -->
      <button
              class="navbar-toggler border py-2 text-dark"
              type="button"
              data-mdb-toggle="collapse"
              data-mdb-target="#navbarLeftAlignExample"
              aria-controls="navbarLeftAlignExample"
              aria-expanded="false"
              aria-label="Toggle navigation"
              >
        <i class="fas fa-bars"></i>
      </button>

      <!-- Collapsible wrapper -->
      <div class="collapse navbar-collapse" id="navbarLeftAlignExample">
        <!-- Left links -->
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">

          <li class="nav-item">
            <a class="nav-link text-dark" aria-current="page" href="{% url 'shop:allprodcat' %}">Home</a>
          </li>



          <!-- Navbar dropdown -->
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarDropdown" role="button" data-mdb-toggle="dropdown" aria-expanded="false">
              Categories
            </a>
            <!-- Dropdown menu -->
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              {% for cat in  links %}
              <li>
                <a class="dropdown-item" href=""{{cat.get_url}}"">{{cat.name}}</a>
              </li>
              {% endfor %}



            </ul>
          </li>
        </ul>
        <!-- Left links -->
      </div>
    </div>
    <!-- Container wrapper -->
  </nav>
  <!-- Navbar -->

  <!-- Heading -->
  <div class="bg-primary">
    <div class="container py-4">
      <!-- Breadcrumb -->
      <nav class="d-flex">
        <h6 class="mb-0">
          <a href="" class="text-white-50">Home</a>
          <span class="text-white-50 mx-2"> > </span>
          <a href="" class="text-white"><u>Shopping cart</u></a>
        </h6>
      </nav>
      <!-- Breadcrumb -->
    </div>
  </div>
  <!-- Heading -->
</header>

<!-- cart + summary -->
<section class="bg-light my-5">
  <div class="container">
    <div class="row">
      <!-- cart -->
      <div class="col-lg-9">
        <div class="card border shadow-0">
          <div class="m-4">
            <h4 class="card-title mb-4">Your shopping cart</h4>
            {% if not cart_items %}
            <h3>your shopping cart is empty</h3>
            <p>please click <a href="{% url 'shop:allprodcat' %}">here</a></p>
            {% else %}
            {% for cart_item in cart_items %}
            <div class="row gy-3 mb-4">
              <div class="col-lg-5">
                <div class="me-lg-5">
                  <div class="d-flex">
                    <a href="cart_item.product.get_absolute_url"><img src="{{cart_item.product.img.url}}" class="border rounded me-3" style="width: 96px; height: 96px;" /></a>
                    <div class="">
                      <a href="cart_item.product.get_absolute_url" class="nav-link">{{cart_item.product.name}}</a>
                      <p class="text-muted">Yellow, Jeans</p>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-lg-2 col-sm-6 col-6 d-flex flex-row flex-lg-column flex-xl-row text-nowrap">
                <div class="">
                 {% if cart_item.quantity < cart_item.product.stock %}
    <a href="{% url 'cart:add_cart' cart_item.product.id %}"><i class="fa-solid fa-square-plus"></i></a>
    <a href="{% url 'cart:remove_cart' cart_item.product.id  %}"><i class="fa-solid fa-minus"></i></a>

                 {% else %}
     <a href="{% url 'cart:remove_cart' cart_item.product.id  %}"><i class="fa-solid fa-minus"></i></a>

                 {% endif %}
                </div>
                <div class="">
                  <text class="h6">{{cart_item.product.price}}</text> <br />
                  <small class="text-muted text-nowrap"> {{cart_item.product.price}} </small>
                </div>
              </div>
              <div class="col-lg col-sm-6 d-flex justify-content-sm-center justify-content-md-start justify-content-lg-center justify-content-xl-end mb-2">
                <div class="float-md-end">
                  <a href="#!" class="btn btn-light border px-2 icon-hover-primary"><i class="fas fa-heart fa-lg px-1 text-secondary"></i></a>
                  <a href="{% url 'cart:full_remove' cart_item.product.id  %}" class="btn btn-light border text-danger icon-hover-danger"> Remove</a>
                </div>
              </div>
            </div>

            {% endfor %}
            {% endif %}




        </div>
      </div>
      <!-- cart -->
      <!-- summary -->
      <div class="col-lg-3">

        <div class="card shadow-0 border">
          <div class="card-body">
            <div class="d-flex justify-content-between">
              <p class="mb-2">Total price:</p>
              <p class="mb-2">{{total}}</p>
            </div>


            <hr />

            <div class="mt-3">
              <a href="#" class="btn btn-success w-100 shadow-0 mb-2"> Make Purchase </a>
              <a href="{% url 'shop:allprodcat' %}" class="btn btn-light w-100 border mt-2"> Back to shop </a>
            </div>
          </div>
        </div>
      </div>
      <!-- summary -->
    </div>
  </div>
</section>
<!-- cart + summary -->


<!-- Footer -->
<footer class="text-center text-lg-start text-muted bg-primary mt-3">
  <!-- Section: Links  -->
  <section class="">
    <div class="container text-center text-md-start pt-4 pb-4">
      <!-- Grid row -->
      <div class="row mt-3">
        <!-- Grid column -->
        <div class="col-12 col-lg-3 col-sm-12 mb-2">
          <!-- Content -->
          <a href="https://mdbootstrap.com/" target="_blank" class="text-white h2">
            MDB
          </a>
          <p class="mt-1 text-white">
            © 2023 Copyright: MDBootstrap.com
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-6 col-sm-4 col-lg-2">
          <!-- Links -->
          <h6 class="text-uppercase text-white fw-bold mb-2">
            Store
          </h6>
          <ul class="list-unstyled mb-4">
            <li><a class="text-white-50" href="#">About us</a></li>
            <li><a class="text-white-50" href="#">Find store</a></li>
            <li><a class="text-white-50" href="#">Categories</a></li>
            <li><a class="text-white-50" href="#">Blogs</a></li>
          </ul>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-6 col-sm-4 col-lg-2">
          <!-- Links -->
          <h6 class="text-uppercase text-white fw-bold mb-2">
            Information
          </h6>
          <ul class="list-unstyled mb-4">
            <li><a class="text-white-50" href="#">Help center</a></li>
            <li><a class="text-white-50" href="#">Money refund</a></li>
            <li><a class="text-white-50" href="#">Shipping info</a></li>
            <li><a class="text-white-50" href="#">Refunds</a></li>
          </ul>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-6 col-sm-4 col-lg-2">
          <!-- Links -->
          <h6 class="text-uppercase text-white fw-bold mb-2">
            Support
          </h6>
          <ul class="list-unstyled mb-4">
            <li><a class="text-white-50" href="#">Help center</a></li>
            <li><a class="text-white-50" href="#">Documents</a></li>
            <li><a class="text-white-50" href="#">Account restore</a></li>
            <li><a class="text-white-50" href="#">My orders</a></li>
          </ul>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-12 col-sm-12 col-lg-3">
          <!-- Links -->
          <h6 class="text-uppercase text-white fw-bold mb-2">Newsletter</h6>
          <p class="text-white">Stay in touch with latest updates about our products and offers</p>
          <div class="input-group mb-3">
            <input type="email" class="form-control border" placeholder="Email" aria-label="Email" aria-describedby="button-addon2" />
            <button class="btn btn-light border shadow-0" type="button" id="button-addon2" data-mdb-ripple-color="dark">
              Join
            </button>
          </div>
        </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row -->
    </div>
  </section>
  <!-- Section: Links  -->

  <div class="">
    <div class="container">
      <div class="d-flex justify-content-between py-4 border-top">
        <!--- payment --->
        <div>
          <i class="fab fa-lg fa-cc-visa text-white"></i>
          <i class="fab fa-lg fa-cc-amex text-white"></i>
          <i class="fab fa-lg fa-cc-mastercard text-white"></i>
          <i class="fab fa-lg fa-cc-paypal text-white"></i>
        </div>
        <!--- payment --->

        <!--- language selector --->
        <div class="dropdown dropup">
          <a class="dropdown-toggle text-white" href="#" id="Dropdown" role="button" data-mdb-toggle="dropdown" aria-expanded="false"> <i class="flag-united-kingdom flag m-0 me-1"></i>English </a>

          <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="Dropdown">
            <li>
              <a class="dropdown-item" href="#"><i class="flag-united-kingdom flag"></i>English <i class="fa fa-check text-success ms-2"></i></a>
            </li>
            <li><hr class="dropdown-divider" /></li>
            <li>
              <a class="dropdown-item" href="#"><i class="flag-poland flag"></i>Polski</a>
            </li>
            <li>
              <a class="dropdown-item" href="#"><i class="flag-china flag"></i>中文</a>
            </li>
            <li>
              <a class="dropdown-item" href="#"><i class="flag-japan flag"></i>日本語</a>
            </li>
            <li>
              <a class="dropdown-item" href="#"><i class="flag-germany flag"></i>Deutsch</a>
            </li>
            <li>
              <a class="dropdown-item" href="#"><i class="flag-france flag"></i>Français</a>
            </li>
            <li>
              <a class="dropdown-item" href="#"><i class="flag-spain flag"></i>Español</a>
            </li>
            <li>
              <a class="dropdown-item" href="#"><i class="flag-russia flag"></i>Русский</a>
            </li>
            <li>
              <a class="dropdown-item" href="#"><i class="flag-portugal flag"></i>Português</a>
            </li>
          </ul>
        </div>
        <!--- language selector --->
      </div>
    </div>
  </div>
</footer>
<!-- Footer -->
    <!-- MDB -->
    <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
    <!-- Custom scripts -->
    <script type="text/javascript" src="{% static 'js/script.js' %}"></script>
    <script src="https://kit.fontawesome.com/1b99dd44bf.js" crossorigin="anonymous"></script>
</body>
</html>